// LIST FILM
export const LIST_FILM = "LIST_FILM"
export const CHANGE_ACTIVE_PAGE = "CHANGE_ACTIVE_PAGE"
export const FILM_REVIEWS = "FILM_REVIEWS"

//FAVORITE FILM
export const ADD_FAVORITE_FILM = "ADD_FAVORITE_FILM"
export const REMOVE_FAVORITE_FILM = "REMOVE_FAVORITE_FILM"